version: '3'
services:

  #################
  # Moodle
  #################

  mariadb:
    image: 'docker.io/bitnami/mariadb:10.10-debian-11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
    # volumes:
    #   - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: 'docker.io/bitnami/moodle:4.0-debian-11'
    ports:
      - '8081:8080'
      - '8444:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb

  #################
  # Wordpress
  #################
  
  mariadb_wp:
    image: 'docker.io/bitnami/mariadb:10.10-debian-11'
    # volumes:
    #   - 'wp_mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'docker.io/bitnami/wordpress:6-debian-11'
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      # - 'wp-content:/var/www/html/wp-content'

    depends_on:
      - mariadb_wp
    environment:
      - MARIADB_HOST=mariadb_wp
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
#   wp_mariadb_data:
#     driver: local
  moodle_data:
    driver: local
#   moodledata_data:
#     driver: local
#   mariadb_data:
#     driver: local
  wordpress_data:
    driver: local